#!/usr/bin/env node
// Computes the version from git tags + Conventional Commits, following the same rules as
// duckAsteroid/gradle-versioning:
//   - base: the last *final* release tag (vX.Y.Z, no suffix) reachable from HEAD; 0.0.0 if none
//   - bump by commits since then: feat → minor; fix/perf → patch;
//     docs/style/refactor/test/chore/build/ci → none; "!" or "BREAKING CHANGE:" → major;
//     non-conventional commits → patch (with a warning); the highest bump wins
//   - HEAD not exactly on a release tag → "-SNAPSHOT"
//
// Usage: node scripts/version.mjs            print the version
//        node scripts/version.mjs --explain  print how it was computed
//        node scripts/version.mjs --write    write src/version.ts (used by the build)
//        node scripts/version.mjs --sync     set package.json "version" (used when packing)
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const RELEASE_TAG = /^v(\d+)\.(\d+)\.(\d+)$/;
const MINOR = new Set(["feat"]);
const PATCH = new Set(["fix", "perf"]);
const NONE = new Set(["docs", "style", "refactor", "test", "chore", "build", "ci", "revert"]);
const RANK = { none: 0, patch: 1, minor: 2, major: 3 };

function git(...args) {
  try {
    return execFileSync("git", args, { cwd: ROOT, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch {
    return null;
  }
}

/** How one commit message bumps the version. */
export function classify(subject, body = "") {
  const m = /^(\w+)(\([^)]*\))?(!)?: \S/.exec(subject);
  if (m?.[3] || /^BREAKING[ -]CHANGE:/m.test(body)) return { bump: "major", type: m?.[1] ?? null };
  if (!m) return { bump: "patch", type: null, nonConventional: true };
  const type = m[1].toLowerCase();
  if (MINOR.has(type)) return { bump: "minor", type };
  if (PATCH.has(type)) return { bump: "patch", type };
  if (NONE.has(type)) return { bump: "none", type };
  return { bump: "patch", type, nonConventional: true };
}

export function computeVersion() {
  const head = git("rev-parse", "HEAD");
  if (!head) return { version: "0.0.0-SNAPSHOT", commit: null, base: null, commits: [], bump: "none", onTag: false, dirty: false };
  // Publishing writes the version into package.json before building, so that change alone
  // doesn't count as uncommitted work.
  const dirty = (git("status", "--porcelain", "--untracked-files=no", "--", ".", ":(exclude)package.json") ?? "") !== "";
  const tags = (git("tag", "--merged", "HEAD", "--list", "v*") ?? "").split("\n").filter((t) => RELEASE_TAG.test(t));
  const parse = (t) => RELEASE_TAG.exec(t).slice(1).map(Number);
  const cmp = (a, b) => a[0] - b[0] || a[1] - b[1] || a[2] - b[2];
  const base = tags.sort((a, b) => cmp(parse(a), parse(b))).pop() ?? null;
  const range = base ? [`${base}..HEAD`] : ["HEAD"];
  const log = git("log", "--format=%h%x1f%s%x1f%b%x1e", ...range) ?? "";
  const commits = log
    .split("\x1e")
    .map((r) => r.trim())
    .filter(Boolean)
    .map((r) => {
      const [sha, subject, body] = r.split("\x1f");
      return { sha, subject, ...classify(subject, body) };
    });
  const bump = commits.reduce((best, c) => (RANK[c.bump] > RANK[best] ? c.bump : best), "none");
  let [major, minor, patch] = base ? parse(base) : [0, 0, 0];
  if (bump === "major") [major, minor, patch] = [major + 1, 0, 0];
  else if (bump === "minor") [minor, patch] = [minor + 1, 0];
  else if (bump === "patch") patch += 1;
  const onTag = base !== null && commits.length === 0;
  const version = `${major}.${minor}.${patch}${onTag && !dirty ? "" : "-SNAPSHOT"}`;
  return { version, commit: head.slice(0, 7), base, commits, bump, onTag, dirty };
}

// Run as a command (not when imported, e.g. by tests).
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const v = computeVersion();
  const arg = process.argv[2];
  for (const c of v.commits.filter((x) => x.nonConventional)) {
    process.stderr.write(`warning: non-conventional commit ${c.sha} "${c.subject}" counted as a patch bump\n`);
  }
  if (arg === "--write") {
    writeFileSync(
      join(ROOT, "src", "version.ts"),
      `// Generated by scripts/version.mjs at build time — do not edit.\nexport const VERSION = ${JSON.stringify(v.version)};\nexport const COMMIT = ${JSON.stringify(v.commit)};\n`,
    );
    process.stdout.write(`${v.version}\n`);
  } else if (arg === "--sync") {
    const pkgPath = join(ROOT, "package.json");
    const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
    pkg.version = v.version;
    writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
    process.stdout.write(`${v.version}\n`);
  } else if (arg === "--explain") {
    const lines = [
      `version:     ${v.version}`,
      `base tag:    ${v.base ?? "(none — starting from 0.0.0)"}`,
      `bump:        ${v.bump}`,
      `on tag:      ${v.onTag}${v.dirty ? " (working tree has uncommitted changes)" : ""}`,
      `commits since base (${v.commits.length}):`,
      ...v.commits.map((c) => `  ${c.sha} ${c.bump.padEnd(5)} ${c.subject}`),
    ];
    process.stdout.write(`${lines.join("\n")}\n`);
  } else {
    process.stdout.write(`${v.version}\n`);
  }
}
